using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using SentiScan.View;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace SentiScan
{
    /// <summary>
    /// Interaction logic for ProductWindow.xaml
    /// </summary>
    public partial class ProductWindow : Window
    {
        private DataTable dtProducts = new DataTable();
        private int _autoGenIndex = 0;



        public ProductWindow()
        {
            InitializeComponent();
            // Retrieve product types from the database
            GetProductsFromDatabase();
        }

        private void MyProducts_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e) 
        {
            
            if (_autoGenIndex == 4) // Assuming the fifth column is Images
            {
                e.Cancel = true; // Cancel the generation of the Images column
            }   

          
            _autoGenIndex++;
        }

        private void MyProducts_AutoGeneratedColumns(object sender, EventArgs e)
        {
            // Reset the index for future auto-generation events
            _autoGenIndex = 0;
        }


        private void AddProductButton_Click(object sender, RoutedEventArgs e)
        {
            ProductAdd productAdd = new ProductAdd();
            productAdd.Show();
            this.Hide();


        }

        private void CloseButton_Click(object sender, RoutedEventArgs e)
        {
            Application.Current.Shutdown();
        }



        public void GetProductsFromDatabase()
        {
            dtProducts = new DataTable(); // reset it cleanly

            using (SqlConnection dbConnection = new SqlConnection(
                $"Server={Properties.Settings.Default.ServerName}; " +
                $"Database={Properties.Settings.Default.DatabaseName}; " +
                $"User Id={Properties.Settings.Default.DatabaseUser}; " +
                $"Password={Properties.Settings.Default.DatabasePass};"))
            {
                try
                {
                    dbConnection.Open();

                    string query = "SELECT * FROM tbl_product_types";
                    using (SqlCommand command = new SqlCommand(query, dbConnection))
                    {
                        SqlDataAdapter dataAdapter = new SqlDataAdapter(command);
                        dataAdapter.Fill(dtProducts);
                    }
                }
                catch (SqlException ex)
                {
                    MessageBox.Show("Error loading products: " + ex.Message);
                }
            }

            // Bind the new table
            MyProducts.ItemsSource = dtProducts.DefaultView;

            // Fit columns
            MyProducts.ColumnWidth = new DataGridLength(1, DataGridLengthUnitType.Star);
        }


        // Back button to go to previous window
        private void BackButton_Click(object sender, RoutedEventArgs e)
        {
            HomeWindow mainWindow = new HomeWindow();
            mainWindow.Show();
            this.Hide();
        }



        private void DeleteProductButton_Click(object sender, RoutedEventArgs e)
        {
            if (MyProducts.SelectedItem is DataRowView selectedRow)
            {
                int productId = Convert.ToInt32(selectedRow["ID"]);
                using (SqlConnection dbConnection = new SqlConnection(string.Format("Server={0}; database={1}; User Id={2}; Password={3};", Properties.Settings.Default.ServerName, Properties.Settings.Default.DatabaseName, Properties.Settings.Default.DatabaseUser, Properties.Settings.Default.DatabasePass)))
                {
                    try
                    {
                        dbConnection.Open();
                        string query = "DELETE FROM tbl_product_types WHERE ID = @ID";
                        using (SqlCommand command = new SqlCommand(query, dbConnection))
                        {
                            command.Parameters.AddWithValue("@ID", productId);
                            int result = command.ExecuteNonQuery();
                            if (result > 0)
                            {
                                MessageBox.Show("Product Deleted Successfully!");
                                // Refresh the product list
                                MyProducts.ItemsSource = null;
                                dtProducts.Clear();
                                GetProductsFromDatabase();
                            }
                        }
                    }
                    catch (SqlException ex)
                    {
                        MessageBox.Show("SQL Exception occurred while trying to delete product." + ex.SqlState);
                    }
                }
            }
            else
            {
                MessageBox.Show("Please select a product to delete.");
            }
        }

        private void Searchbtn_Click(object sender, RoutedEventArgs e)
        {
            string searchText = txtSearch.Text.Trim().ToLower();
            if (string.IsNullOrEmpty(searchText))
            {
                // If search text is empty, show all products
                MyProducts.ItemsSource = dtProducts.DefaultView;
            }
            else
            {
                // Filter the DataTable based on the search text
                DataView dv = dtProducts.DefaultView;
                dv.RowFilter = $"Name LIKE '%{searchText}%' OR Description LIKE '%{searchText}%'";
                MyProducts.ItemsSource = dv;
            }
        }

        private void txtSearch_TextChanged(object sender, TextChangedEventArgs e)
        {
            // Hide textbox text when user clicks into it

            if (!string.IsNullOrEmpty(txtSearch.Text) && txtSearch.Text.Length > 0)
            {
                textSearch.Visibility = Visibility.Collapsed;
            }
            else
            {
                textSearch.Visibility = Visibility.Visible;
            }
        }

        private void textSearch_MouseDown(object sender, MouseButtonEventArgs e)
        {
            txtSearch.Focus();
        }

        private void Refreshbtn_Click(object sender, RoutedEventArgs e)
        {
            DataView dv = dtProducts.DefaultView;
            dv.RowFilter = string.Empty;
            MyProducts.ItemsSource = dv;
        }


        private void EditButton_Click(object sender, RoutedEventArgs e)
        {
            if (MyProducts.SelectedItem == null)
            {
                MessageBox.Show("Please select a product to edit.");
                return;
            }

            DataRowView row = MyProducts.SelectedItem as DataRowView;
            int id = Convert.ToInt32(row["ID"]);

            EditProductWindow editWindow = new EditProductWindow(id);


            bool? result = editWindow.ShowDialog();
            if (result == true)
            {
                GetProductsFromDatabase();
            }

        }

    }
}
