using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using SentiScan.View;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace SentiScan
{
    /// <summary>
    /// Interaction logic for ProductWindow.xaml
    /// </summary>
    public partial class ProductWindow : Window
    {
        DataTable dtProductTypes = new DataTable();
        private int _autoGenIndex = 0;



        public ProductWindow()
        {
            InitializeComponent();
            // Retrieve product types from the database
            GetProductsFromDatabase();
        }

        private void MyProducts_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e) 
        {
            // Cancel auto-generation for specific columns
            if (_autoGenIndex == 0) // Assuming the first column is ID
            {
                e.Cancel = true; // Cancel the generation of the ID column
            }

            _autoGenIndex++;
        }

        private void MyProducts_AutoGeneratedColumns(object sender, EventArgs e)
        {
            // Reset the index for future auto-generation events
            _autoGenIndex = 0;
        }


        private void AddProductButton_Click(object sender, RoutedEventArgs e)
        {
            ProductAdd productAdd = new ProductAdd();
            productAdd.Show();
            this.Close();


        }

        private void CloseButton_Click(object sender, RoutedEventArgs e)
        {
            Application.Current.Shutdown();
        }

        public void GetProductsFromDatabase()
        {
            using (SqlConnection dbConnection = new SqlConnection(string.Format("Server={0}; database={1}; User Id={2}; Password={3};", Properties.Settings.Default.ServerName, Properties.Settings.Default.DatabaseName, Properties.Settings.Default.DatabaseUser, Properties.Settings.Default.DatabasePass)))
            {
                try
                {
                    dbConnection.Open();
                    string query = "SELECT * FROM tbl_product_types";
                    using (SqlCommand command = new SqlCommand(query, dbConnection))
                    {


                        // create data adapter
                        SqlDataAdapter dataAdapter = new SqlDataAdapter(command);
                        // this will query your database and return the result to your datatable
                        dataAdapter.Fill(dtProductTypes);
                        dbConnection.Close();
                        dataAdapter.Dispose();
                    }
                }
                catch (SqlException ex)
                {
                    MessageBox.Show("UserCheck: SQL Exception occurred while trying retrieve tbl_product_types." + ex.SqlState);
                }
            }

            // Check if any rows exist
            if (dtProductTypes.Rows.Count > 0)
            {
                // Bind the DataTable to the DataGrid
                MyProducts.ItemsSource = dtProductTypes.DefaultView;
                
            }

            if (MyProducts.Columns.Count > 0)
            {
                // Hide unwanted columns
                MyProducts.Columns[0].Visibility = Visibility.Collapsed; // Assuming the first column is ID
            }
        }

        // Back button to go to previous window
        private void BackButton_Click(object sender, RoutedEventArgs e)
        {
            HomeWindow mainWindow = new HomeWindow();
            mainWindow.Show();
            this.Close();
        }



        private void DeleteProductButton_Click(object sender, RoutedEventArgs e)
        {
            if (MyProducts.SelectedItem is DataRowView selectedRow)
            {
                int productId = Convert.ToInt32(selectedRow["ID"]);
                using (SqlConnection dbConnection = new SqlConnection(string.Format("Server={0}; database={1}; User Id={2}; Password={3};", Properties.Settings.Default.ServerName, Properties.Settings.Default.DatabaseName, Properties.Settings.Default.DatabaseUser, Properties.Settings.Default.DatabasePass)))
                {
                    try
                    {
                        dbConnection.Open();
                        string query = "DELETE FROM tbl_product_types WHERE ID = @ID";
                        using (SqlCommand command = new SqlCommand(query, dbConnection))
                        {
                            command.Parameters.AddWithValue("@ID", productId);
                            int result = command.ExecuteNonQuery();
                            if (result > 0)
                            {
                                MessageBox.Show("Product Deleted Successfully!");
                                // Refresh the product list
                                MyProducts.ItemsSource = null;
                                dtProductTypes.Clear();
                                GetProductsFromDatabase();
                            }
                        }
                    }
                    catch (SqlException ex)
                    {
                        MessageBox.Show("SQL Exception occurred while trying to delete product." + ex.SqlState);
                    }
                }
            }
            else
            {
                MessageBox.Show("Please select a product to delete.");
            }
        }
    }
}